[package]
name = "gitmoji"
version = "1.1.1"
authors = ["Jonas Geschke <github@yonny.de>"]
edition = "2018"
license = "MIT"
description = "CLI for gitmoji"
homepage = "https://github.com/kegesch/gitmoji-cli"
repository = "https://github.com/kegesch/gitmoji-cli"
documentation = "https://docs.rs/gitmoji-cli"

[dependencies]
clap = { version = "2.33", features = ["yaml", "wrap_help"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
spinners = "2.0"
dirs = "4.0"
json = "0.12"
colored = "2.0"
once_cell = "1.8"
dialoguer = { git = "https://github.com/mitsuhiko/dialoguer", version = "0.8", features = ["fuzzy-select"] }
confy = "0.4"
serde_derive = "1.0"
serde = "1.0"
